<a href="https://colab.research.google.com/github/Gwonyoungleader/Python-for-Data-analysis/blob/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EB%8B%A8%EA%B3%84/9%EC%9B%94_24%EC%9D%BC_%EB%B6%96%EA%BD%83_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
import pandas as pd

In [158]:
data = pd.read_csv('/iris.csv')

In [159]:
data = data.sample(frac=1)

In [160]:
train_data= data.drop(['variety'],axis=1)
train_labels = data['variety']

In [161]:
import numpy as np

In [162]:
train_labels = train_labels.to_numpy()

In [163]:
from keras.utils.np_utils import to_categorical

In [164]:
def one_hot_vectorize(sequences,dimension=3):
    results = np.zeros((len(sequences),dimension))
    
    for i in range(150):
        
        
        if str(sequences[i]) == 'Virginica':
            results[i,0] = 1.
        elif str(sequences[i]) == 'versicolor':
            results[i,1] = 1.
        elif str(sequences[i]) =='Setosa':
            results[i,2] = 1.
    return results                


In [165]:
train_labels = one_hot_vectorize(train_labels)

In [166]:
from sklearn.preprocessing import MinMaxScaler

minmax_scalar = MinMaxScaler()
train_data = minmax_scalar.fit_transform(train_data)

In [167]:
test_labels = train_labels[121:]
test_data = train_data[121:]
train_data = train_data[:121]
train_labels = train_labels[:121]


In [168]:
from keras import models
from keras import layers

def build_model():
    model = models.Sequential()
    model.add(layers.Dense(16, activation='relu',
                           input_shape = (train_data.shape[1],)))
    model.add(layers.Dense(16,activation='relu'))

    model.add(layers.Dense(3, activation = 'softmax'))
    model.compile(optimizer='rmsprop',
                  loss = 'categorical_crossentropy',
                  metrics = ['accuracy'])
    return model

In [181]:
k = 4 
num_val_samples = len(train_data) // k 
num_epochs = 10
all_scores = []
all_scores2 = []
for i in range(k):
    print('처리중인 폴드: #',i)
    val_data = train_data[i * num_val_samples: (i+1) * num_val_samples]
    val_labels = train_labels[i * num_val_samples: (i+1)*num_val_samples]

    partial_train_data = np.concatenate([train_data[:i*num_val_samples],
                                         train_data[(i+1)*num_val_samples:]],
                                        axis = 0)
    
    partial_train_labels = np.concatenate([train_labels[:i*num_val_samples],
                                         train_labels[(i+1)*num_val_samples:]],
                                        axis = 0)
    print(type(partial_train_data))
    model = build_model()
    model.fit(partial_train_data, partial_train_labels,
              epochs = num_epochs, batch_size = 4, validation_data=(val_data,val_labels))
    val_loss, val_acc = model.evaluate(val_data,val_labels,verbose = 0)
    all_scores.append(val_loss)
    all_scores2.append(val_acc)

    

처리중인 폴드: # 0
<class 'numpy.ndarray'>
Epoch 1/10
23/23 [==============================] - 0s 6ms/step - loss: 0.5819 - accuracy: 0.9341 - val_loss: 0.4476 - val_accuracy: 0.9667
Epoch 2/10
23/23 [==============================] - 0s 2ms/step - loss: 0.5151 - accuracy: 0.9670 - val_loss: 0.4029 - val_accuracy: 1.0000
Epoch 3/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4745 - accuracy: 1.0000 - val_loss: 0.3641 - val_accuracy: 1.0000
Epoch 4/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4302 - accuracy: 1.0000 - val_loss: 0.3463 - val_accuracy: 1.0000
Epoch 5/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4050 - accuracy: 1.0000 - val_loss: 0.3178 - val_accuracy: 1.0000
Epoch 6/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3746 - accuracy: 1.0000 - val_loss: 0.2993 - val_accuracy: 1.0000
Epoch 7/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3519 - accuracy: 1.0000 - val_loss: 0.2860 - val_

In [170]:
all_scores
print(all_scores2)

[1.0, 1.0, 1.0, 1.0]


In [171]:
print(all_scores)

[0.05632421746850014, 0.08090338110923767, 0.06345489621162415, 0.11045432090759277]


np.mean(all_scores2)


In [182]:
predictions = model.predict(test_data)

In [183]:
pred_results = np.zeros((len(predictions),3))
for i,sequence in enumerate(predictions):
    if sequence[0] >= 0.5:
        pred_results[i,0] = 1.
    elif sequence[1] >= 0.5:
        pred_results[i,1] = 1.
    else:
        pred_results[i,2] = 1.

In [184]:
print(pred_results)


[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [180]:
print(test_labels)

[[0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
